# Generated by Django 5.1.7 on 2025-04-10 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_historicalaccount_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HistoricalAccountTransactionHistory",
        ),
    ]
