# Generated by Django 5.2 on 2025-04-12 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_historicalwithdraw"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AccountTransactionHistory",
        ),
    ]
