# Generated by Django 5.2 on 2025-05-07 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_delete_accounttransactionhistory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={"permissions": [("can_view_icon", "Can view icon")]},
        ),
        migrations.AlterModelOptions(
            name="accounttransfer",
            options={"permissions": [("can_view_icon", "Can view icon")]},
        ),
        migrations.AlterModelOptions(
            name="withdraw",
            options={"permissions": [("can_view_icon", "Can view icon")]},
        ),
    ]
