# Generated by Django 5.2 on 2025-05-07 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "account",
            "0006_alter_account_options_alter_accounttransfer_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={
                "permissions": [("can_view_icon_account", "Can view icon account")]
            },
        ),
        migrations.AlterModelOptions(
            name="accounttransfer",
            options={
                "permissions": [
                    ("can_view_icon_account_transfer", "Can view icon account transfer")
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="withdraw",
            options={
                "permissions": [("can_view_icon_withdraw", "Can view icon withdraw")]
            },
        ),
    ]
