# Generated by Django 5.1.7 on 2025-04-08 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipt", "0001_initial"),
        ("sale_invoice", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipt",
            name="sales_invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receipts",
                to="sale_invoice.salesinvoice",
            ),
        ),
    ]
