# Generated by Django 5.2 on 2025-05-07 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("receipt", "0002_historicalreceipt"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="receipt",
            options={"permissions": [("can_view_icon", "Can view icon")]},
        ),
    ]
