# Generated by Django 5.2 on 2025-05-07 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("receipt", "0003_alter_receipt_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="receipt",
            options={
                "permissions": [("can_view_icon_receipt", "Can view icon receipt")]
            },
        ),
    ]
