version: '3.8'

services:
  web:
    build: .
    container_name: django_app
    expose:
      - "9000"
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./staticfiles:/app/staticfiles
    depends_on:
      - web
