version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             gunicorn mssports.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env
    restart: always

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/staticfiles
    ports:
      - 80:80
    depends_on:
      - web
    restart: always

volumes:
  static_volume:
