# Generated by Django 5.2 on 2025-04-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_historicalcustomer"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="whole_sale",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalcustomer",
            name="whole_sale",
            field=models.BooleanField(default=False),
        ),
    ]
