# Generated by Django 5.2 on 2025-04-21 14:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0003_customer_whole_sale_historicalcustomer_whole_sale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="mobile_number",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be in the format: '0XXXXXXXXX'. Exactly 10 digits starting with 0.",
                        regex="^0\\d{9}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="historicalcustomer",
            name="mobile_number",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be in the format: '0XXXXXXXXX'. Exactly 10 digits starting with 0.",
                        regex="^0\\d{9}$",
                    )
                ],
            ),
        ),
    ]
