# Generated by Django 5.2 on 2025-05-07 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0004_alter_customer_mobile_number_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={"permissions": [("can_view_icon", "Can view icon")]},
        ),
    ]
