# Generated by Django 5.2 on 2025-04-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_historicalcategory_historicalproduct"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproduct",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
