# Generated by Django 5.2 on 2025-04-25 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_historicalproduct_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["name"]},
        ),
    ]
