# Generated by Django 5.2 on 2025-05-07 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_alter_category_options_alter_product_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "permissions": [("can_view_icon_category", "Can view icon category")],
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name"],
                "permissions": [("can_view_icon_product", "Can view icon product")],
            },
        ),
    ]
