# Generated by Django 5.2 on 2025-04-15 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("payment", "0002_historicalpayment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalpayment",
            name="purchase_invoice",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="purchase_invoice",
        ),
        migrations.AddField(
            model_name="historicalpayment",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="historicalpayment",
            name="object_id",
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="content_type",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="object_id",
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
    ]
