# Generated by Django 5.2 on 2025-05-07 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_remove_historicalpayment_purchase_invoice_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"permissions": [("can_view_icon", "Can view icon")]},
        ),
    ]
