# Generated by Django 5.2 on 2025-05-07 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0004_alter_payment_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={
                "permissions": [("can_view_icon_payment", "Can view icon payment")]
            },
        ),
    ]
