# Generated by Django 5.1.7 on 2025-04-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounttransfer",
            name="transferred_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="withdraw",
            name="withdrawn_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
