# Generated by Django 5.1.7 on 2025-04-04 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_accounttransactionhistory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accounttransactionhistory",
            options={
                "ordering": ["-timestamp"],
                "verbose_name_plural": "Account histories",
            },
        ),
    ]
