# Generated by Django 5.1.7 on 2025-04-08 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stocktransfer",
            name="to_shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incoming_transfers",
                to="shop.shop",
            ),
        ),
    ]
