# Generated by Django 5.1.7 on 2025-03-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_delete_payment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
        migrations.AddField(
            model_name="product",
            name="profit_margin",
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
    ]
