# Generated by Django 5.1.7 on 2025-03-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_remove_product_price_product_profit_margin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseinvoice",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2, default=0.0, editable=False, max_digits=10
            ),
        ),
    ]
