# Generated by Django 5.2 on 2025-04-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_historicalstock_historicalstocktransfer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalstocktransfer",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="stocktransfer",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
