# Generated by Django 5.2 on 2025-05-07 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_alter_historicalstocktransfer_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stock",
            options={"permissions": [("can_view_icon", "Can view icon")]},
        ),
        migrations.AlterModelOptions(
            name="stocktransfer",
            options={"permissions": [("can_view_icon", "Can view icon")]},
        ),
    ]
