# Generated by Django 5.2 on 2025-05-07 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_alter_stock_options_alter_stocktransfer_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stock",
            options={"permissions": [("can_view_icon_stock", "Can view icon stock")]},
        ),
        migrations.AlterModelOptions(
            name="stocktransfer",
            options={
                "permissions": [
                    ("can_view_icon_stock_transfer", "Can view icon stock transfer")
                ]
            },
        ),
    ]
