# Generated by Django 5.1.7 on 2025-03-31 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0006_product_description_alter_purchaseinvoiceitem_price_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesinvoice",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2, default=0.0, editable=False, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoiceitem",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoiceitem",
            name="sales_invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="inventory.salesinvoice",
            ),
        ),
    ]
