# Generated by Django 5.1.7 on 2025-03-31 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_alter_salesinvoice_total_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="credit",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
