# Generated by Django 5.1.7 on 2025-04-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_salesinvoice_paid_amount_receipt"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="code",
            field=models.CharField(default="shop", max_length=255),
            preserve_default=False,
        ),
    ]
