# Generated by Django 5.1.7 on 2025-04-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_shop_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocktransfer",
            name="description",
            field=models.CharField(default="test", max_length=255),
            preserve_default=False,
        ),
    ]
