# Generated by Django 5.1.7 on 2025-04-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_stocktransfer_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesinvoice",
            name="due_date",
            field=models.DateTimeField(default="2000-01-29"),
            preserve_default=False,
        ),
    ]
