# Generated by Django 5.1.7 on 2025-04-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0012_salesinvoice_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesinvoice",
            name="due_date",
            field=models.DateField(),
        ),
    ]
