# Generated by Django 5.1.7 on 2025-04-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0013_alter_salesinvoice_due_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="black_list",
            field=models.BooleanField(default=False),
        ),
    ]
