# Generated by Django 5.1.7 on 2025-04-01 19:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0014_customer_black_list"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="contact_info",
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="contact_info",
        ),
        migrations.AddField(
            model_name="customer",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="mobile_number",
            field=models.CharField(
                default="021548965",
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be in the format: '0XXXXXXXXX'. Exactly 10 digits starting with 0.",
                        regex="^0\\d{9}$",
                    )
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="supplier",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="supplier",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="supplier",
            name="mobile_number",
            field=models.CharField(
                default="058964785",
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be in the format: '0XXXXXXXXX'. Exactly 10 digits starting with 0.",
                        regex="^0\\d{9}$",
                    )
                ],
            ),
            preserve_default=False,
        ),
    ]
