# Generated by Django 5.1.7 on 2025-04-03 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("inventory", "0015_remove_customer_contact_info_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="receipt",
            name="payment_method",
        ),
        migrations.AddField(
            model_name="receipt",
            name="account",
            field=models.ForeignKey(
                default=4,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account",
                to="accounts.account",
            ),
            preserve_default=False,
        ),
    ]
