# Generated by Django 5.1.7 on 2025-04-04 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entity", "0001_initial"),
        ("inventory", "0016_remove_receipt_payment_method_receipt_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesinvoice",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="entity.customer",
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoiceitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="entity.product"
            ),
        ),
        migrations.AlterField(
            model_name="purchaseinvoiceitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="entity.product"
            ),
        ),
        migrations.AlterField(
            model_name="stocktransferitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="entity.product"
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="entity.product"
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="entity.shop"
            ),
        ),
        migrations.AlterField(
            model_name="stocktransfer",
            name="to_shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incoming_transfers",
                to="entity.shop",
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="entity.shop"
            ),
        ),
        migrations.AlterField(
            model_name="stocktransfer",
            name="from_shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outgoing_transfers",
                to="entity.shop",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseinvoice",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="entity.shop"
            ),
        ),
        migrations.AlterField(
            model_name="purchaseinvoice",
            name="supplier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="entity.supplier",
            ),
        ),
        migrations.DeleteModel(
            name="Customer",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.DeleteModel(
            name="Shop",
        ),
        migrations.DeleteModel(
            name="Supplier",
        ),
    ]
