# Generated by Django 5.1.7 on 2025-04-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0017_alter_salesinvoice_customer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="average_cost",
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stock",
            name="selling_price",
            field=models.DecimalField(decimal_places=2, default=15, max_digits=10),
            preserve_default=False,
        ),
    ]
