# Generated by Django 5.1.7 on 2025-04-04 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_account_name"),
        ("inventory", "0018_stock_average_cost_stock_selling_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipt",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_payments",
                to="accounts.account",
            ),
        ),
    ]
