# Generated by Django 5.1.7 on 2025-04-07 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0019_alter_receipt_account"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Receipt",
        ),
    ]
