# Generated by Django 5.1.7 on 2025-04-07 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0020_delete_receipt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseinvoiceitem",
            name="purchase_invoice",
        ),
        migrations.RemoveField(
            model_name="purchaseinvoiceitem",
            name="product",
        ),
        migrations.DeleteModel(
            name="PurchaseInvoice",
        ),
        migrations.DeleteModel(
            name="PurchaseInvoiceItem",
        ),
    ]
