# Generated by Django 5.1.7 on 2025-04-07 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entity", "0004_supplier_payable"),
        ("inventory", "0021_remove_purchaseinvoiceitem_purchase_invoice_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stocktransfer",
            name="to_shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incoming_transfers",
                to="entity.product",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stock",
            unique_together={("shop", "product")},
        ),
    ]
