# Generated by Django 5.1.7 on 2025-04-08 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0022_alter_stocktransfer_to_shop_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salesinvoice",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="salesinvoice",
            name="shop",
        ),
        migrations.RemoveField(
            model_name="salesinvoiceitem",
            name="sales_invoice",
        ),
        migrations.RemoveField(
            model_name="salesinvoiceitem",
            name="product",
        ),
    ]
