# Generated by Django 5.1.7 on 2025-04-08 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0023_remove_salesinvoice_customer_and_more"),
        ("receipt", "0002_alter_receipt_sales_invoice"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SalesInvoice",
        ),
        migrations.DeleteModel(
            name="SalesInvoiceItem",
        ),
    ]
