# Generated by Django 5.1.7 on 2025-04-08 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0024_delete_salesinvoice_delete_salesinvoiceitem"),
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="shop.shop"
            ),
        ),
        migrations.AlterField(
            model_name="stocktransfer",
            name="from_shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outgoing_transfers",
                to="shop.shop",
            ),
        ),
    ]
