# Generated by Django 5.2 on 2025-05-07 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expense", "0002_alter_expense_paid_amount_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expense",
            options={"permissions": [("can_view_icon", "Can view icon")]},
        ),
    ]
