# Generated by Django 5.2 on 2025-05-07 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expense", "0003_alter_expense_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expense",
            options={
                "permissions": [("can_view_icon_expense", "Can view icon expense")]
            },
        ),
    ]
