# Generated by Django 5.2 on 2025-04-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sale_invoice", "0002_historicalsalesinvoice_historicalsalesinvoiceitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsalesinvoiceitem",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="historicalsalesinvoiceitem",
            name="discount_method",
            field=models.CharField(
                choices=[("amount", "Amount"), ("percentage", "Percentage")],
                default="amount",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="salesinvoiceitem",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="salesinvoiceitem",
            name="discount_method",
            field=models.CharField(
                choices=[("amount", "Amount"), ("percentage", "Percentage")],
                default="amount",
                max_length=10,
            ),
        ),
    ]
