# Generated by Django 5.2 on 2025-04-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sale_invoice", "0003_historicalsalesinvoiceitem_discount_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsalesinvoiceitem",
            name="average_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="salesinvoiceitem",
            name="average_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
