# Generated by Django 5.2 on 2025-05-07 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sale_invoice", "0004_historicalsalesinvoiceitem_average_cost_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="salesinvoice",
            options={"permissions": [("can_view_icon", "Can view icon")]},
        ),
    ]
