# Generated by Django 5.2 on 2025-05-07 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sale_invoice", "0005_alter_salesinvoice_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="salesinvoice",
            options={
                "permissions": [
                    ("can_view_icon_sale_invoice", "Can view icon sale invoice")
                ]
            },
        ),
    ]
