# Generated by Django 5.2 on 2025-05-07 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_alter_historicalshop_location_alter_shop_location"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shop",
            options={"permissions": [("can_view_icon", "Can view icon")]},
        ),
    ]
