# Generated by Django 5.2 on 2025-05-07 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_alter_shop_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shop",
            options={"permissions": [("can_view_icon_shop", "Can view icon shop")]},
        ),
    ]
