# Generated by Django 5.2 on 2025-04-25 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0003_alter_historicalsupplier_mobile_number_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="supplier",
            options={"ordering": ["name"]},
        ),
    ]
