# Generated by Django 5.2 on 2025-05-07 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0004_alter_supplier_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="supplier",
            options={
                "ordering": ["name"],
                "permissions": [("can_view_icon", "Can view icon")],
            },
        ),
    ]
