# Generated by Django 5.2 on 2025-05-07 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0005_alter_supplier_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="supplier",
            options={
                "ordering": ["name"],
                "permissions": [("can_view_icon_supplier", "Can view icon supplier")],
            },
        ),
    ]
