# Generated by Django 5.1.7 on 2025-04-06 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("entity", "0002_category_product_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="parent",
        ),
    ]
