# Generated by Django 5.1.7 on 2025-04-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entity", "0003_remove_category_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="payable",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
