# Generated by Django 5.1.7 on 2025-04-08 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("entity", "0004_supplier_payable"),
        ("inventory", "0025_alter_stock_shop_alter_stocktransfer_from_shop"),
        ("purchase_invoice", "0003_alter_purchaseinvoice_shop"),
        ("sale_invoice", "0002_alter_salesinvoice_shop"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Shop",
        ),
    ]
