# Generated by Django 5.1.7 on 2025-04-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase_invoice", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseinvoice",
            name="paid_amount",
            field=models.DecimalField(
                decimal_places=2, default=0.0, editable=False, max_digits=10
            ),
        ),
    ]
