# Generated by Django 5.2 on 2025-05-07 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchase_invoice", "0002_historicalpurchaseinvoice_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="purchaseinvoice",
            options={"permissions": [("can_view_icon", "Can view icon")]},
        ),
    ]
