# Generated by Django 5.1.7 on 2025-04-08 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase_invoice", "0002_purchaseinvoice_paid_amount"),
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseinvoice",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="shop.shop"
            ),
        ),
    ]
