# Generated by Django 5.2 on 2025-05-07 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchase_invoice", "0003_alter_purchaseinvoice_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="purchaseinvoice",
            options={
                "permissions": [
                    ("can_view_icon_purchase_invoice", "Can view icon purchase invoice")
                ]
            },
        ),
    ]
